# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sum_cols <- function(input) {
    .Call(`_dfStats_sum_cols`, input)
}

sum_rows <- function(input) {
    .Call(`_dfStats_sum_rows`, input)
}

check_numeric <- function(x) {
    .Call(`_dfStats_check_numeric`, x)
}

